{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}

package:
  name: geneinfo
  version: {{ pyproject.get("project").get("version") }}

source:
  git_url: https://github.com/munch-group/geneinfo.git

build:
  # noarch: python
  number: 0
  # script: $PYTHON -m pip install . -vv
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:       # your library dependencies
    - python
    - jupyter
    - ipython
    - matplotlib>=3.0
    - seaborn
    - numpy>=1.1
    - requests
    - biopython
    - goatools>=1.2
    - pytables
    - wget
    - pydot
    - statsmodels
    - rapidfuzz
    - tqdm

channels:    # your library dependencies
  - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build>=25.1.3 # from 25 the output file is a .conda not .tar.bz2
  - conda-verify
  
test:
  imports:
    - geneinfo
  # commands:
  #   - exercises --help    

about:
  home: https://github.com/munch-group/geneinfo.git
  license: MIT
  # summary: "Blah blah"
  # description: |
  #   "Blah blah"
  #   "Blah blah"
  dev_url: https://github.com/munch-group/geneinfo.git
  doc_url: https://munch-group.org/geneinfo
