{% set data = load_setup_py_data() %}

package:
  name: geneinfo
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/geneinfo.git

build:
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:       # your library dependencies
    - python
    - jupyter
    - ipython
    - matplotlib>=3.0
    - numpy>=1.1
    - requests
    - biopython
    - goatools>=1.2
    - pytables
    - wget

channels:    # your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify
  
test:
  imports:
    - geneinfo
  # commands:
  #   - exercises --help    

about:
  home: https://github.com/munch-group/geneinfo.git
  license: MIT
  # summary: "Blah blah"
  # description: |
  #   "Blah blah"
  #   "Blah blah"
  dev_url: https://github.com/munch-group/geneinfo.git
  doc_url: https://munch-group.org/geneinfo
