{% set data = load_setup_py_data() %}

package:
  name: geneinfo
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/geneinfo.git

build:
  skip: True  # [win]
  noarch: python
  number: 0
  # script: python -m pip install --no-deps --ignore-installed .
  # script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  script: "{{ PYTHON }} -m pip install . -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter
    - ipython
    - matplotlib>=3.0
    - numpy>=1.1
    - requests
    - biopython
    - goatools>=1.2
    - wget

channels:    # write here the list of channels to look for your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  
test:
  imports:
    - geneinfo
  # commands:
  #   - exercises --help    

about:
  home: https://github.com/munch-group/geneinfo
  license: MIT
  summary: 'summary'
  description: |
    Description.
