{% set version = "3.4.9" %}

package:
  name: geneinfo
  version: {{ version }}

source:
  git_url: https://github.com/kaspermunch/geneinfo.git

build:
  noarch: python
  number: 0
  # script: python -m pip install --no-deps --ignore-installed .
  # entry_points:
  #   - print-steps = bp_help.print_steps:run_student_file
  #   - myiagi = bp_help.text_gui:run

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter
    - ipython
    - matplotlib>=3.0
    - numpy>=1.1
    - requests
    - biopython
    - goatools>=1.2
    - wget

# channels:
#   - defaults
#   - conda-forge
#   - bioconda

test:
  imports:
    - geneinfo

about:
  home: https://github.com/kaspermunch/geneinfo.git
  # license: MIT
  summary: 'summary'
  description: |
    Description.


# package:
#   name: bp-help
#   version: "0.3"

# source:
#   path: ../

# requirements:
#   build:
#     - python
#   run:
#     - python #>=3.9, <=3.11
#     - pygments
#     - textual
#     - rich
#     - art

# channels:
#   - defaults
#   - conda-forge
#   - sepandhaghighi

# about:
#   home: https://github.com/kaspermunch/bp-help
#   license: MIT

# build:
#   script: python -m pip install . -vv
#   noarch: python

# test:
#   imports:
#     - bp-help

